[package]
name = "gyges_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
min-max = "0.1"
rand = "0.8.5"
mimalloc = { version = "*", default-features = false}
minimax = "0.3.0"

[profile.release]
lto = true
code_gen_units = 1
panic = "abort"
